[pytest]
# Changed timeout to 60s and added --clean-alluredir
addopts = -n 3 --timeout=60 --alluredir=allure-results --clean-alluredir --html=reports/report.html

# ✅ Discovery: Tells pytest exactly where to look for tests
testpaths = tests

# ✅ Logging: Shows INFO logs in the console during execution
log_cli = true
log_cli_level = INFO